### ISSUE TITLE
Runtime error 12

### ISSUE THREAD

**Issue by mattgara** [gunrock/graphblast#23]
Hi,

I tried compiling this against CUDA 11.0 on Ubuntu 18.04 with the nvidia HPC SDK version 2021_212, and running 

```
../bin/gbfs ../data/small/chesapeake.mtx
````

prints a plethora of error messages:
```
Runtime error: reduceInner(val, accum, op, &u->sparse_, desc) returned 12 at /home/mgara/software/graphblast/./graphblas/backend/cuda/operations.hpp:1012
```
none of which are very informative. At this point I assume this project is highly experimental and unstable?

**Comment by ctcyang** [comment]
Sorry for taking a while on this one. Yes, this project is experimental and may be unstable. This PR should fix that bug.
