### ISSUE TITLE
Installation fault 

### ISSUE THREAD

**Issue by Pogozhelskaya** [gunrock/graphblast#4]
I was trying to install GraphBlast on Ubuntu 16.04, checked software versions (CUDA 9.1, Boost 1.58, g++ 4.9.3) and followed the instruction step by step, but got the [errors](https://pastebin.com/YSrMTqHV).

Also, the flags recommended in this [issue](https://github.com/tensorflow/tensorflow/issues/1066) didn't help.

**Comment by ctcyang** [comment]
Looking at the error log, this line says you are using g++ 5.x:

` /usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(36): error: identifier "__builtin_ia32_monitorx" is undefined`

Could you verify you are using g++ 4.9.3 by doing g++ -v?

If you are changing between g++ versions, you need to delete the CMakeCache.txt and CMakeFiles directory before doing `cmake ..` again.

**Comment by Pogozhelskaya** [comment]
Yes, you are right, the compiler identification was 5.x. I checked all versions again, fixed this problem, but there are still [errors](https://paste.ofcode.org/9h5CxnZm6zQMGQD9icCVFS).

**Comment by ctcyang** [comment]
Sorry, I was busy for the last little while. Are you still getting the same error? I have not encountered your error before, but I would perhaps try adding the flags recommended in this [issue](https://github.com/tensorflow/tensorflow/issues/1066), clearing the CMakeCache.txt and CMakeFiles directory before redoing `cmake ..`.
